on: [push]

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        flutter-sdk-version: ["stable", "beta", "3.7.7"]
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter SDK
        uses: ./
        with:
          flutter-sdk-version: ${{ matrix.flutter-sdk-version }}
      - run: flutter --version
      - run: flutter doctor
